[build]
  command = "npm install"
  publish = "."

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "PORT,NODE_ENV,ADMIN_URL,CLIENT_URL"
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
