[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = ".env.example,seed.js,package-lock.json"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
